### PR TITLE
Add ability to change cache on and off when streaming

### PR DESCRIPTION
**Pull request by arj03**
~~I have also added two tests that shows the overhead of caching.~~

### CODE REVIEW

**Comment by arj03** [comment]
Sorry this is a bit of a mess of many commits. The end result should be good now. I can do another PR to squash the commits into 1 if needed.

**Comment by dominictarr** [comment]
this is a breaking change, correct? I've merged, added you as npm owner so you can bump version and publish

**Comment by arj03** [comment]
Yes it is a breaking change in that is expects the underlying stream to have a different api. So it's dependant on https://github.com/flumedb/flumelog-offset/pull/10.

**Comment by dominictarr** [comment]
@arj03 okay, publish away

**Pull request merged**
